---
title: Yeastwranglers Www
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Yeast Wranglers
description: Yeast Wranglers www
url: 
source: src
destination: dist
exclude:
- assets
author:
  name: chrisvdp
  email: chris@chrisvdp.com
  uri: 
  bio: 
  twitter: yeastwranglers
future: true
show_drafts: true
lsi: false
limit_posts: 10
permalink: none
paginate: 10
paginate_path: "/blog/page:num/"
excerpt_separator: "<!--more-->"
markdown: redcarpet
redcarpet:
  extensions:
  - no_intra_emphasis
  - tables
  - fenced_code_blocks
  - autolink
  - smart
  - strikethrough
  - superscript
  - underline
  - highlight
  - footnotes
highlighter: true
gems:
- jekyll-archives
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll-sitemap
jekyll-archives:
  enabled:
  - year
  - month
  - categories
  - tags
  layouts:
    year: year-archive
    month: month-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    year: "/archive/:year/"
    month: "/archive/:year/:month/"
    category: "/category/:name/"
    tags: "/tag/:name/"
